<a href="https://colab.research.google.com/github/Fl0rin09/Data-structure/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 #def iteration (array):
array=[1,2,3,4,5,6]
for i in range (len(array)):
  print(array[i], end=" ")
#

1 2 3 4 5 6 

In [ ]:
#reverse
for i in range (len(array)-1,-1,-1):
  print(array[i], end=" ")

6 5 4 3 2 1 

In [ ]:
#copy array
new_array=[None]*len(array)
for i in range (len(new_array)):
   new_array[i]=array[i]
   print(new_array)

[1, None, None, None, None, None]
[1, 2, None, None, None, None]
[1, 2, 3, None, None, None]
[1, 2, 3, 4, None, None]
[1, 2, 3, 4, 5, None]
[1, 2, 3, 4, 5, 6]


In [ ]:
#new reverse array
rev_array=[None]*len(array)
a=len(array)
for i in range (a):
  rev_array[i]=array[a-1]
  a-=1
  print(rev_array)

[6, None, None, None, None, None]
[6, 5, None, None, None, None]
[6, 5, 4, None, None, None]
[6, 5, 4, 3, None, None]
[6, 5, 4, 3, 2, None]
[6, 5, 4, 3, 2, 1]


In [ ]:
# left shift
array=[1,2,3,4,5,6]
for i in range(1,len(array)):
  array[i-1]=array[i]
array[len(array)-1]=None
print(array)


[2, 3, 4, 5, 6, None]


In [ ]:
#right shift
array=[1,2,3,4,5,6]
for i in range(len(array)-1,0,-1):
  array[i]=array[i-1]
array[0]=None
print(array)

[None, 1, 2, 3, 4, 5]


In [ ]:
# remove elem
array=[1,2,3,4,5,6]
index=2
for i in range(index+1,len(array)):
  array[i-1]=array[i]
array[len(array)-1]=None
print(array)

[1, 2, 4, 5, 6, None]


In [ ]:
#Task-1
def playRight (seq,beat):
  seq=[10,20,30,40,50,60]
  beat=[1,0,0,1,0,1]

  for i in range









print(playRight(sequence,beats))



SyntaxError: ignored

In [ ]:
#Test 03: Merge Lineup
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np
def mergeLineup(pokemon_1, pokemon_2):
  result = [None]*len(pokemon_1) #this array stores the resulting array
  # TO DO


  for i in range(len(pokemon_1)):
    pokemon_1[i] = 0 if pokemon_1[i] == None else pokemon_1[i]
    pokemon_2[i] = 0 if pokemon_2[i] == None else pokemon_2[i]

  #ans_array = np.zeros(n, dtype=int)
  for i in range(len(pokemon_1)):
    ans_array[i] = pokemon_1[i] + pokemon_2[len(pokemon_1)- i - 1]

  return ans_array


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

In [ ]:
#task-3
pk_1= [4, 5, -1, None, None]
pk_2= [2, 27, 7, 12, None]
merge=[0]*len(pk_1)

for i in range (len(pk_1)):
  #for j in range (len(pk_2)-1,-1,-1):
    if pk_1[i]== None:
      pk_1[i]=0
    if pk_2[i]== None:
      pk_2[i]=0

for i in range (len(pk_1)):
    merge[i]=pk_1[i] + pk_2[(len(pk_1))-1-i]
print(merge)

[4, 17, 6, 27, 2]


In [ ]:
def balance_salami(salami):


  sum=0
  for i in range (len(salami)):
    sum+=salami[i]
  if sum%2!=0:
    return False

  half=sum//2
  a=0
  for i in range(len(salami)):
    a+=salami[i]
    if a==half:
      return True

  return False



salami= [10,3,1,2,10]
balance_salami(salami)


True

220 lab1 task 5

In [ ]:
arr = [4,5,6,6,4,3,6,4]

uni_arr = [0]*len(arr)
j=0
for i in range(len(arr)):     # unique number tracing
  if arr[i] not in uni_arr:
    uni_arr[j]=arr[i]
    j+=1

print(j,uni_arr)

num = [0]*j
for i in range(j):             #jist elem
  num[i]=uni_arr[i]

print(num)

fre = [0]*len(num)

for i in range(len(num)):
  for j in arr:            # koto bar ache
    if num[i]==j:
      fre[i]+=1
print(fre)
for i in range(len(fre)):
  for j in range(i+1,len(fre)):
    if fre[i]==fre[j] and fre[i]>=2:
      print(True)



4 [4, 5, 6, 3, 0, 0, 0, 0]
[4, 5, 6, 3]
[3, 1, 3, 1]
True


In [ ]:
# multiplication
import numpy as np

m1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
m2 = np.array([[90,80,70],[60,50,40],[30,20,10]])

res = np.zeros((3,3),dtype=int)

sum = 0
for i in range(len(m1)):
  for c in range(len(m1)):
    for j in range(len(m2)):
      res[i][c]+= m1[i][j] * m2[j][c]

for i in range(len(res)):
  print(res[i])

[3000 2400 1800]
[8400 6900 5400]
[13800 11400  9000]


In [ ]:
#row ke col and col ke row
import numpy as np
a=np.array([[2,4,6],[1,3,5]])
row,col=a.shape
print(a)
new=np.zeros((col,row),dtype=int)
print(new)
for i in range (len(new)):
  for j in range (len(a)):
    new[i][j]=a[j][i]

print(new)

[[2 4 6]
 [1 3 5]]
[[0 0]
 [0 0]
 [0 0]]
[[2 1]
 [4 3]
 [6 5]]


In [ ]:
import numpy as np
a=[10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
sum=0
for i in range (len(a)):
  sum+=a[i]
av=sum/len(a)    #x'

sum2=0
for i in range (len(a)):
  sum2+=((a[i]-av)**2)

s=(sum2/(len(a)-1))**0.5    #sqroot of x-x'/n-1
print(av,s)

count=0
n=[0]*len(a)
for i in range (len(a)):
  if a[i] > av+ 1.5*s or  a[i] < av-1.5*s:          #  x=x'+ 1.5*s
    n[count]=a[i]
    count+=1

new=[0]*count
for i in range (count) :
  new[i]=n[i]
print(new)


In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#Test 03: Merge Lineup
import numpy as np
def mergeLineup(pokemon_1, pokemon_2):
  result = [None]*len(pokemon_1) #this array stores the resulting array
  # TO DO


  for i in range (len(pokemon_1)):
      if pokemon_1[i]== None:
        pokemon_1[i]=0
      if pokemon_2[i]== None:
        pokemon_2[i]=0

  for i in range (len(pokemon_1)):
     result[i]=pokemon_1[i] + pokemon_2[(len(pokemon_1))-1-i]    # [last elem= len(a)-1]

  return result


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Test 03: Merge Lineup  ///
Task 3: [12, 3, 28, -8, 5]
Not Accepted [Your output: [12, 3, 28, -8, 5]  |  Expected Output: [12  3 28 -8  5]]
Task 3: [4, 17, 6, 27, 2]
Not Accepted [Your output: [4, 17, 6, 27, 2]  |  Expected Output: [ 4 17  6 27  2]]


In [ ]:
import numpy as np
def std_div_away(a):

    sum=0
    for i in range (len(a)):
      sum+=a[i]
      av=sum/len(a)    #x'

    sum2=0
    for i in range (len(a)):
      sum2+=((a[i]-av)**2)

    s=(sum2/(len(a)-1))**0.5    #sqroot of x-x'/n-1
    print(av,s)

    count=0
    n=[0]*len(a)
    for i in range (len(a)):
      if a[i] > av+ 1.5*s or  a[i] < av-1.5*s:          #  x=x'+ 1.5*s
        n[count]=a[i]
        count+=1

    new=[0]*count
    for i in range (count) :
      new[i]=n[i]
    return new
array=[10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
print(std_div_away(array))

In [ ]:
cards=[1,2,3,2,8,2,2,5,7]
number=2
i=0
while i<len(cards):

  if cards[i]==number:
    for j in range (i+1,len(cards)):
      cards[j-1]=cards[j]
    cards[len(cards)-1]=0

  if cards[i]==number:
    i+=1

In [ ]:
# Test 05: Protecc Salami
def protectSalami(salami):
  # TO DO

  uni_array = [0]*len(salami)
  count=0
  for i in range(len(salami)):
    if salami[i] not in uni_array:
      uni_array[count]=salami[i]
      count+=1
  new = [0]*count
  for i in range(count):
    new[i]=uni_array[i]

  n=[0]*len(new)
  for i in range(len(new)):
    for j in range (len(salami)):
      if new[i]==salami[j]:
        n[i]+=1

  for i in range(len(n)):
    for j in range(i+1,len(n)):
      if n[i]==n[j] and n[i]>=2:
         return True

  return False

print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

In [ ]:
#odd-even
a=[2,12,3,8,1,5]
new=[0]*len(a)

for i in range (1,len(a)):
  if a[i]!=0 and a[i+1]==0:
    a[i]=a[i+1]
    a[i+1]=a[i]
  else:
    a[i]=a[i]
print(a)

In [ ]:
def walk_zigzag(matrix):
    result = []
    m, n = len(matrix), len(matrix[0])

    for i in range(m):
        if i % 2 == 0:
            for j in range(n):
                if matrix[i][j] % 2 == 0:
                    result.append(matrix[i][j])
        else:
            for j in range(n - 1, -1, -1):
                if matrix[i][j] % 2 == 0:
                    result.append(matrix[i][j])

    return result

floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

#print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)


In [ ]:
def calculate_strength_diff(clubroom):
    size = len(clubroom)
    strength_diff = []

    for i in range(size):
        for j in range(size):
            if i != j:
                crow_strength = clubroom[i][j]
                cat_strength = clubroom[j][i]
                strength_diff.append(crow_strength - cat_strength)

    return strength_diff
#(row*(row-1))/2=upper right corner er element
row*row+1= all matrix value
# Sample Input
clubroom = [
    [1, 2, 9, 7],
    [4, 5, 1, 8],
    [3, 6, 2, 7],
    [2, 8, 6, 3]
]

# Get the strength difference
strength_diff = calculate_strength_diff(clubroom)

# Print the strength difference array
print(strength_diff)

In [ ]:
def atm_triangle(rows):
    triangle = [[1] * n for n in range(1, rows + 1)]

    for i in range(2, rows):
        for j in range(1, i):
            triangle[i][j] = triangle[i - 1][j - 1] + triangle[i - 1][j]

    return triangle

def print_atm_triangle(triangle):
    for row in triangle:
        print(" ".join(map(str, row)))

# Sample Input
num_rows = 5

# Generate ATM's Triangle
atm = atm_triangle(num_rows)

# Print the ATM's Triangle
print_atm_triangle(atm)


In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  if type(m) != np.ndarray:
    return
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

In [ ]:
def walk_zigzag(floor):
  #To Do
  row,col = floor.shape
  matx = np.zeros((col,row), dtype=int)

  for i in range(col):
    for j in range(row):
      matx[i,j]=floor[j,i]
  print(matx)

  for i in range(col):
    if i%2==0:
      for j in range(row):
        if j%2==0:
           print(matx[i][j],end=" ")
      print()

    else:
      for j in range(row-1,-1,-1):
        if j%2 != 0:
           print(matx[i][j],end=" ")
      print()



floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

In [ ]:
def walk_zigzag(floor):
  #To Do
  row,col=floor.shape
  print(row,col)   #4,5
  for i in range (col):  #5
    if i%2==0:
      for j in range(row,2):
        print(floor[j][i])
    else:
      if row%2==0:
        for j in range (row-1,0,-2):
            print(floor[j][i])
      else:
        for j in range (row-2,0,-2):
          print(floor[j][i])
    pass



floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )



print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

In [ ]:
import numpy as np
depth=2
district = np.array([
                 [2,3,4,1],
                 [3,4,6,5],
                 [2,1,4,7]
                ])
district_row, district_col = district.shape
    #TO DO
arr=np.zeros((district_row+(depth*2),district_col+(depth*2)),dtype=int)
row,col=arr.shape

for i in range (row):
  for j in range (col):
    arr[i][j]=8


for i in range (district_row):
  for j in range (district_col):
     arr[i+depth][j+depth]=district[i][j]

print(arr)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 2 3 4 1 8 8]
 [8 8 3 4 6 5 8 8]
 [8 8 2 1 4 7 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]


In [ ]:
def find_subarray_with_sum(arr, target_sum):
    current_sum = 0
    start, end = 0, 0

    for end in range(len(arr)):
        current_sum += arr[end]

        while current_sum > target_sum:
            current_sum -= arr[start]
            start += 1

        if current_sum == target_sum:
            return start + 1, end + 1  # Adding 1 to convert 0-based indexing to 1-based indexing

    return -1  # If no subarray is found

# Example 1
arr1 = [1, 2, 3, 7, 5]
target_sum1 = 12
result1 = find_subarray_with_sum(arr1, target_sum1)
print("Example 1:", result1)  # Output: (2, 4)

# Example 2
arr2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
target_sum2 = 15
result2 = find_subarray_with_sum(arr2, target_sum2)
print("Example 2:", result2)  # Output: (1, 5)

Example 1: (2, 4)
Example 2: (1, 5)


In [ ]:
a=[10,30,50,70,90]
b=[100,80,60,40,20]

n=(len(a)+len(b))
new=[0]*n
for i in range (len(a)):
  new[i]=a[i]
for j in range(len(b)):
  new[len(a)+j]=b[j]
print(new)

for i in range (len(new)):
  for j in range (i+1,len(new),1):
    if new[i]>new[j]:
      new[i]=new[j]

print(new)


[10, 30, 50, 70, 90, 100, 80, 60, 40, 20]


IndexError: ignored

In [ ]:
print(6**3)

216
